### ISSUE TITLE
Issue with grabAddressInfo instance declaration

### ISSUE THREAD

**Issue by daveasiamah** [sesesmith30/ghanapost-address#5]
I was thinking the usage example could read like this:
const ghpost = require("ghpost-address");
const addr = new ghpost;

function getAddressInfo(){ addr.grabAddressInfo("AK-507-4460").then(function(res) {
	return console.log(res);
}).catch(function (err){
return console.log(err)
)
}
getAddressInfo ();

**Comment by sesesmith30** [comment]
corrected
